vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    uploads:
      uri_prefix: /images/uploads
      upload_destination: "%kernel.project_dir%/public/images/uploads"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
